version: "3.8"
services:
  messagedb:
    image: mongo:latest
    container_name: "messagedb"
    ports:
      - '27017:27017'

  redis:
    image: 'redis:latest'
    ports:
      - '6379'

  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: "rabbitmq"
    ports:
      - '5672:5672'
      - '15672:15672'