version: "3.8"

services:
  post-message-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: hacee/post-message-service:v1.0.0
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://messagedb:27017/messagedb
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_DATA_REDIS_HOST=redis

    ports:
        - '8000:8080'

  messagedb:
    image: mongo:latest
    ports:
      - '27017:27017'

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

  rabbitmq:
    image: rabbitmq:management
    restart: no
    ports:
      - '5672:5672'
      - '15672:15672'